services:
  web:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app      # rm in prod
      - venv:/app/.venv  # rm in prod
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        
        - action: rebuild
          path: pyproject.toml

        - action: rebuild
          path: uv.lock # Ensure dependencies are reinstalled when lock file changes
          
    ports:
      - "8000:8000"
    env_file:
      - .envrc.dev # change to prod in prod
volumes: # rm in prod
  venv: {}  # rm in prod
